ecommerce/common/urls.py
from django.urls import path
from . import views
app_name = 'common'
urlpatterns = [
    path('master1',views.common_master,name='master1'),
    path('home1',views.common_home,name='home1'),
    path('custlogin1',views.common_custlogin,name='custlogin1'),
    path('sellogin1',views.common_sellogin,name='sellogin1'),
    path('custreg1',views.common_custreg,name='custreg1'),
    path('selreg1',views.common_selreg,name='selreg1'),
    path('emailexist',views.email_exists,name='email_exists'),
]

ecommerce/customer/urls.py
from django.urls import path
from . import views
app_name = 'customer'
urlpatterns = [
    path('master2',views.customer_master,name='master2'),
    path('home2',views.customer_home,name='home2'),
    path('productdetail',views.customer_product_details,name='productdetail'),
    path('myorder',views.customer_myorder, name='myorder'),
    path('profile',views.customer_profile,name='profile'),
    path('change_password',views.change_password,name='change_password'),
    path('logout',views.logout,name='logout'),
    path('view_pro/<int:product_id>',views.view_products,name='viewpro'),
    path('add_to_cart/<int:product_id>',views.add_to_cart,name='addtocart'),
    path('cart',views.customer_cart,name='cart'),
    path('change_quantity',views.change_quantity,name='change_quantity')
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include ('common.urls')),
    path('customer/',include ('customer.urls')),
    path('seller/',include ('seller.urls')),
    path('school_api/',include ('school_api.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'
urlpatterns = [
    path('master3',views.seller_master,name='master3'),
    path('home3',views.seller_home,name='home3'),
    path('viewpro',views.seller_viewpro,name='viewpro'),
    path('addpro',views.seller_addpro,name='addpro'),
    path('profile',views.seller_profile,name='profile'),
    path('viewpayment',views.seller_viewpayment,name='viewpayment'),
    path('vieworder',views.seller_vieworder,name='vieworder'),
    path('logout',views.logout,name='logout'),
    path('deletepro/<int:p_id>',views.del_product,name='deletepro'),
    path('updatestock',views.seller_updatestock,name='updatestock'),
    path('get_product',views.get_product,name='get_product'),
    
]

ecommerce/common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(max_length=30)
    customer_email = models.CharField(max_length=50)
    customer_password = models.CharField(max_length=30)
    customer_address = models.CharField(max_length=300)
    customer_phoneno = models.CharField(max_length=20)

class Seller(models.Model):
    seller_name=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    phone=models.CharField(max_length=18)
    address=models.CharField(max_length=200)
    account_holder_name=models.CharField(max_length=60)
    ifsc_code=models.CharField(max_length=50)
    bank_branch=models.CharField(max_length=100)
    account_number=models.CharField(max_length=50)
    seller_username = models.CharField(max_length=30)
    seller_password = models.CharField(max_length=50)
    seller_pic = models.ImageField(upload_to='seller/')

ecommerce/common/views.py
import random
from django.http import JsonResponse
from django.shortcuts import render,redirect

from common.models import Customer,Seller
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
def common_master(request):
    return render(request,'common/master1.html')

def common_home(request):
    return render(request,'common/home1.html')

def common_custlogin(request):
    msg = ""
    if request.method == 'POST':
        cust_email1 = request.POST['c_email1'] #input variable login ullath
        cust_pass1 = request.POST['c_pass1']
        
        try : 
            customer = Customer.objects.get(
                customer_email = cust_email1,  
                customer_password = cust_pass1
                )          
            request.session['customer'] = customer.id
            return redirect ('customer:productdetail')
        except :
            msg = 'invalid password or username'
            
    return render(request,'common/custlogin1.html')

def common_custreg(request):
    if request.method == 'POST':
        cust_name = request.POST ['c_name']
        cust_email = request.POST ['c_email']
        cust_pass = request.POST ['c_password']
        cust_address = request.POST ['c_address']
        cust_phone = request.POST ['c_phone']
        
        # QUICK FIX KODUKANM
        customer1 = Customer(
            customer_name = cust_name,
            customer_email = cust_email,
            customer_password = cust_pass,
            customer_address = cust_address,
            customer_phoneno = cust_phone
            # models il ullath = views il ullath
        )
        customer1.save()
        
        return redirect ('customer:home2')
    return render(request,'common/custreg1.html')

def common_sellogin(request):
    msg = ""
    if request.method == 'POST':
        username = request.POST['s_username'] #input variable login ullath
        password = request.POST['s_password']
        print(password)
        # try : 
        seller= Seller.objects.get(seller_username=username,seller_password=password)          
        request.session['seller'] = seller.id
        return redirect ('seller:home3')
        # except :
        #     msg = 'invalid password or username'
    return render(request,'common/sellogin1.html',{'msg':msg})

def common_selreg(request):
    if request.method == 'POST':
        seller_name = request.POST['sel_name']
        seller_phone = request.POST['sel_phone']
        seller_address = request.POST['sel_address']
        seller_holder_name = request.POST['holder_name']
        seller_ifsc = request.POST['sel_ifsc']
        seller_branch = request.POST['sel_branch']
        seller_accno = request.POST['sel_accno']
        seller_email = request.POST['sel_email']
        photo = request.FILES['pic']
        seller_username = random.randint(1111,9999)
        seller_password = 'sel-'+ seller_name.lower() + str(seller_username)
        message = 'hai your username is' + str(seller_username)+'and temporary password is ' + seller_password 
        
        newseller = Seller(
            seller_name = seller_name,
            phone = seller_phone,
            address = seller_address,
            account_holder_name = seller_holder_name,
            ifsc_code = seller_ifsc,
            bank_branch = seller_branch,
            account_number = seller_accno,
            email = seller_email,
            seller_username = seller_username,
            seller_password = seller_password,
            seller_pic = photo
        )
        send_mail(
            'username and temporary password',
            message,
            settings.EMAIL_HOST_USER,
            [seller_email],
            fail_silently=False
        )
        newseller.save()
    return render(request,'common/selreg1.html')

def email_exists(request):
    email = request.POST['email_key']
    e_exist = Customer.objects.filter(customer_email = email).exists()
    return JsonResponse ({'status':e_exist})

ecommerce/common/templates/common/custlogin1.html
{% extends 'common/master1.html' %}
{% load static %}
{% block content %}
<center><h1>Customer Login Here</h1></center>
<div class="col-md-6" style="margin: auto;" >
  {{ msg }}
<form method= "POST" enctype="multipart/form-data">
  {% csrf_token %}
    <!-- Email input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">Email address</label>
      <input type="email" id="form2Example1" class="form-control"  name="c_email1" />
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example2">Password</label>
      <input type="password" id="form2Example2" class="form-control"  name="c_pass1" />
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
          <label class="form-check-label" for="form2Example31"> Remember me </label>
        </div>
      </div>
  
      <div class="col">
        <!-- Simple link -->
        <a href="#!">Forgot password?</a>
      </div>
    </div>
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'common:custreg1' %}">Register</a></p>
  </form></div>
{% endblock %}

ecommerce/common/templates/common/custreg1.html
{% extends 'common/master1.html' %}
{% load static %}
{% block content %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form class="mx-1 mx-md-4" method= "POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example1c">Your Name</label>
                        <input type="text" id="form3Example1c" class="form-control" / name="c_name">
                        
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example3c">Your Email</label>
                        <input type="email" id="cust_email" class="form-control" / name="c_email">
                        <span id="msg"></span>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example4c">Password</label>
                        <input type="password" id="form3Example4c" class="form-control" / name="c_password">
                        
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example4cd">Address</label>
                        <input type="text" id="form3Example4cd" class="form-control" / name="c_address">
                        
                      </div>
                    </div>
                    
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example4cd">Phone Number</label>
                        <input type="text" id="form3Example4cd" class="form-control" / name="c_phone">
                        
                      </div>
                    </div>
  
                    <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                      <label class="form-check-label" for="form2Example3">
                        I agree all statements in <a href="#!">Terms of service</a>
                      </label>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>
  
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ajax for if cust email already exist pop the msg ,ajax mostly have 3 parts 1.type,2.url,3.data -->
  <!-- ajax use aakne page mothayit reload aakande cheriya oru part execute aakan -->
  <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
      })
      $('#cust_email').change(function(){
        var email = $('#cust_email').val()
        $.ajax({
          type:'POST',
          url:"{% url 'common:email_exists' %}",
          data:{'email_key':email}, 
          success:function (response){
            if (response.status == true)
            {
              $('#msg').html("Email already exists")
              $('#msg').css("color","red")
            }
            else
            {
              $('#msg').html("Email available")
              $('#msg').css("color","black")
            }
          }
        })
      })
    })
  </script>
  {% endblock %}

ecommerce/common/templates/common/home1.html
{% extends 'common/master1.html' %}
{% load static %}
{% block content %}

<div class="container">
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner" >
      <div class="carousel-item active">
        <img src="{% static '/images/car2.jpg' %}" class="d-block w-100" alt="..." width="500" height="400">
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/car3.jpg' %}" class="d-block w-100" alt="..." width="500" height="400">
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/car1.jpg'%}" class="d-block w-100" alt="..." width="500" height="400">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
  {% endblock %}

ecommerce/common/templates/common/master1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="">ShOpium</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Wishlist</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search"> 
            <button class="btn btn-outline-danger" type="submit">Bag</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>&nbsp;&nbsp;&nbsp;
              <a href="{% url 'customer:logout' %}"><button class="btn btn-secondary" type="submit">logout</button></a>
            </form>
          </div>
        </div>
      </nav>
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'common:custlogin1' %}">Customer login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'common:custreg1' %}">Customer registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'common:sellogin1' %}">Seller login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'common:selreg1' %}">Seller registration</a>
        </li>
      </ul>
      {% block content %}
      {% endblock %}
      <center><h1>THANK YOU</h1></center>
</body>
</html>

ecommerce/common/templates/common/sellogin1.html
{% extends 'common/master1.html' %}
{% load static %}
{% block content %}
<center><h1>Seller Login Here</h1></center>
<div class="col-md-6" style="margin: auto;" >
<form method="POST" enctype="multipart/form-data"> 
{% csrf_token %}
    <!-- Email input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">Username</label>
      <input type="text" id="form2Example1" name='s_username' class="form-control" />
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example2">Password</label>
      <input type="password" id="form2Example2" name="s_password" class="form-control" />
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="form2Example31"  checked />
          <label class="form-check-label" for="form2Example31"> Remember me </label>
        </div>
      </div>
  
      <div class="col">
        <!-- Simple link -->
        <a href="#!">Forgot password?</a>
      </div>
    </div>
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
    {{msg}}
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'common:selreg1' %}">Register</a></p>
  </form></div>
{% endblock %}

ecommerce/common/templates/common/selreg1.html
{% extends 'common/master1.html' %}
{% load static %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="container">
  <div class="row p-7">
      <div class="col-md-4"></div>
      <div class="col-md-4">
          <div class="card">
              <div class="card-body">
                <h5 class="card-title text-center">Sellers Register</h5>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">seller name</label>
                  <input type="text" class="form-control" id="validationCustom01" required name='sel_name'>
                </div>
                
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">phone</label>
                  <input type="text" class="form-control" id="validationCustom01" required name='sel_phone'>
                </div>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">address</label>
                  <input type="text" class="form-control" id="validationCustom01" required name='sel_address'>
                </div>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">account holdername</label>
                  <input type="text" class="form-control" id="validationCustom01" required name="holder_name">
                </div>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">IFSC code</label>
                  <input type="text" class="form-control" id="validationCustom01" required name="sel_ifsc">
                </div>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">bank branch</label>
                  <input type="text" class="form-control" id="validationCustom01" required name="sel_branch">
                </div>
                <div class="col-md-12">
                  <label for="validationCustom01" class="form-label">account number</label>
                  <input type="text" class="form-control" id="validationCustom01" required name="sel_accno">
                </div>
                <div>
                  <label for="validationCustom01" class="form-label">Email</label>
                   <input type="email" class="form-control" id="validationCustom01" required name="sel_email">
                 </div><br>
                 <div class="row mb-3">
                  <label for="inputEmail3" class="col-sm-2 col-form-label"  >photo</label>
                  <div class="col-sm-10">
                    <input type="file" class="form-control" id="inputEmail3" name="pic">
                  </div>
                </div>
                <div class="col-md-12 py-3">
                  <button type="submit" class="btn btn-primary w-100"><a href="{% url 'seller:viewpro' %} ">Submit</button>
                </div>
                <a href="{% url 'common:sellogin1' %}" class="card-link"><h5 class="text-center">Log in</h5></a>
              </div>
            </div>
      </div>
      <div class="col-md-4"></div>
  </div>
</div>
</form>
  {% endblock %}