ecommerce/common/urls.py
from django.urls import path
from . import views
app_name = 'common'
urlpatterns = [
    path('master1',views.common_master,name='master1'),
    path('home1',views.common_home,name='home1'),
    path('custlogin1',views.common_custlogin,name='custlogin1'),
    path('sellogin1',views.common_sellogin,name='sellogin1'),
    path('custreg1',views.common_custreg,name='custreg1'),
    path('selreg1',views.common_selreg,name='selreg1'),
    path('emailexist',views.email_exists,name='email_exists'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include ('common.urls')),
    path('customer/',include ('customer.urls')),
    path('seller/',include ('seller.urls')),
    path('school_api/',include ('school_api.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'
urlpatterns = [
    path('master3',views.seller_master,name='master3'),
    path('home3',views.seller_home,name='home3'),
    path('viewpro',views.seller_viewpro,name='viewpro'),
    path('addpro',views.seller_addpro,name='addpro'),
    path('profile',views.seller_profile,name='profile'),
    path('viewpayment',views.seller_viewpayment,name='viewpayment'),
    path('vieworder',views.seller_vieworder,name='vieworder'),
    path('logout',views.logout,name='logout'),
    path('deletepro/<int:p_id>',views.del_product,name='deletepro'),
    path('updatestock',views.seller_updatestock,name='updatestock'),
    path('get_product',views.get_product,name='get_product'),
    
]

ecommerce/seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.
class Product(models.Model):
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE, default='')
    category = models.CharField(max_length=50)
    product_name = models.CharField(max_length=50)
    product_no = models.CharField(max_length=18)
    description = models.CharField(max_length=200)
    price = models.FloatField(max_length=60)
    current_stock = models.CharField(max_length=50)
    product_pic = models.ImageField(upload_to='product/')

ecommerce/seller/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from seller.decorator import auth_seller

from seller.models import Product

# Create your views here.
def seller_master(request):
    return render(request,'seller/master3.html')

@auth_seller
def seller_addpro(request):
    if request.method == 'POST':
        category = request.POST ['p_category']
        pro_name = request.POST ['p_name']
        pro_no = request.POST ['p_number']
        description = request.POST ['p_description']
        price = request.POST ['p_price']
        stock = request.POST ['p_stock']
        photo = request.FILES['p_image']
        #namal kodukkunna variable = requst .post ['form il ullath']
        
        
        # QUICK FIX KODUKANM
        #ith object aan =Classname
        #models = new varaible ivde koduthe
        newproduct = Product(
            category = category,
            product_name =pro_name,
            product_no = pro_no,
            description = description,
            price = price,
            current_stock = stock,
            product_pic = photo,
            seller_id_id = request.session['seller']
        )
        newproduct.save()
    return render(request,'seller/add_product.html')

@auth_seller
def seller_home(request):
    return render(request,'seller/home3.html')

@auth_seller
def seller_profile(request):
    return render(request,'seller/profile.html')

@auth_seller
def seller_vieworder(request):
    return render(request,'seller/view_order.html')

@auth_seller
def seller_viewpro(request):
    seller_product = Product.objects.filter(
        seller_id = request.session['seller']  
    )
    return render(request,'seller/view_product.html',{'products' : seller_product })

@auth_seller
def seller_viewpayment(request):
    return render(request,'seller/view_payment.html')

def logout(request):
    del request.session['seller']
    # return render (request,'common/custlogin1.html')
    return redirect('common:sellogin1')

@auth_seller
def del_product(request,p_id):
    delete_product = Product.objects.get(id = p_id)
    delete_product.delete()
    return redirect('seller:viewpro')

@auth_seller
def seller_updatestock(request):
    return render(request,'seller/update_stock.html')

@auth_seller
def get_product(request):
    category = request.POST['category_key']
    product = Product.objects.filter(seller_id= request.session ['seller'],category = category )
                                                                            #models=ivde ulla category
    data = [{'product_name':pro.product_name,'id':pro.id}
            for pro in product]
    return JsonResponse({'data':data})

ecommerce/seller/templates/seller/add_product.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
<h1 style="text-align: center; margin-top: 20px;">Product List</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div style="width: 50%; margin-left: auto; margin-right: auto; ">
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label" >Category</label>
        <div class="col-sm-10">
            <!-- <input type="dropdown" class="form-control" id="nameField" placeholder="product type"><br> -->
            <select class="form-select form-control" name="p_category" aria-label="Default select example"><br><br>
                <option selected> Select Category</option>
                <option value="1">Mobile</option>
                <option value="2">Laptop</option>
                <option value="3">Desktop</option>
                <option value="3">Mobile Accessories</option>
                <option value="3">Computer Accessories</option>      
                <option value="3">Laptop Accessories</option>


              </select>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label" >Product Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="nameField" placeholder="Product" name="p_name"><br>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Product No</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="nameField" placeholder="" name="p_number"><br>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="descriptionField" placeholder="Write Description" rows="3"
                style="margin-bottom: 20px;" name="p_description"></textarea>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="pricefield" placeholder="₹" name="p_price"><br>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Current Stock</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="stockField" placeholder="Count" name="p_stock"><br>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Upload image</label>
        <div class="col-sm-10">
            <input type="file" class="form-control" id="stockField" placeholder="Count" name="p_image"><br>
        </div>
    </div>
    <div class="">
        <div class="col-sm-10" style="width: 100%">
            <button type="submit" class="btn btn-primary" style="width: 50%; margin-left: 40%; "
                >Add Product</button>
        </div>
    </div>
</div>
</form>
{% endblock %}

ecommerce/seller/templates/seller/home3.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
seller home
{% endblock %}

ecommerce/seller/templates/seller/master3.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</head>

<body>
    <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'seller:home3' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:addpro' %}">Add Product</a>
        </li><li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'seller:vieworder' %}">View orders</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'seller:viewpro' %}">View products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'seller:viewpayment' %}">View payments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'seller:updatestock' %}">Update Stock</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:profile' %}">Profile</a>
        </li>     
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:logout' %}">Logout</a>
        </li>
        </ul>


      {% block content %}
{% endblock %}
</body>

</html>

ecommerce/seller/templates/seller/profile.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
seller profile
{% endblock %}

ecommerce/seller/templates/seller/update_stock.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
<h1 style="text-align: center; margin-top: 20px;">Update Stock</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div style="width: 50%; margin-left: auto; margin-right: auto; ">
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label" >Category</label>
        <div class="col-sm-10">
           
            <select class="form-select form-control" name="p_category" aria-label="Default select example" id='category'><br><br>
                <option selected> Select Category</option>
                <option value="1">Mobile</option>
                <option value="2">Laptop</option>
                <option value="3">Desktop</option>
                <option value="4">Mobile Accessories</option>
                <option value="5">Computer Accessories</option>      
                <option value="6">Laptop Accessories</option>
              </select>
        </div>
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label" >Products</label>
            <div class="col-sm-10">
                <!-- <input type="dropdown" class="form-control" id="nameField" placeholder="product type"><br> -->
                <select class="form-select form-control" name="product" id="product" aria-label="Default select example"><br><br>
                   
                  </select>
            </div>
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label" id="stock">Current Stock</label>
                <div class="col-sm-10">
                  
                    <!-- <input type="dropdown" class="form-control" id="nameField" placeholder="product type"><br> -->
                
                </div><div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label" >New Stock</label>
                    <div class="col-sm-10">
                        <!-- <input type="dropdown" class="form-control" id="nameField" placeholder="product type"><br> -->
                       <input type="text">
                    </div>

                    <button type="submit" class="btn btn-danger">Update</button>
    </div>
    
        
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
      })
      $('#category').change(function(){
       var category = $('#category').val()
       console.log(category)
        $.ajax({
          type:'POST',
          url:"{% url 'seller:get_product' %}",
          data:{'category_key':category},
          success:function (response){
           console.log(response.data)
           data=response.data
            $('#product option'  ).remove()
            string1 = ''
            for (i of data){
                string1 += `
                        <option value=${i.id}">${i.product_name}</option>
                        `
            }

            $("#product").append(string1)
          }
        })
      })
    })
  </script>
  <script>
    $(document).ready(function(){
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
      })
      $('#stock').change(function(){
        var stock = $('#stock').val()
        console.log(category)
         
          })
        })
  
  
  </script>
  
{% endblock %}

ecommerce/seller/templates/seller/view_order.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
seller view orders
{% endblock %}

ecommerce/seller/templates/seller/view_payment.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}
seller view payment
{% endblock %}

ecommerce/seller/templates/seller/view_product.html
{% extends 'seller/master3.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row">




    <div class="container-fluid bg-trasparent my-4 p-3" style="position: relative;">

      <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
        {% for products in products %}
        <div class="col">
          <div class="card h-100 shadow-sm">
            <img src="{{products.product_pic.url}}" class="card-img-top" alt="...">
            <div class="card-body">
              <div class="clearfix mb-3">
              </div>
              <h4 class="card-title text-center">{{products.product_name|title}}</h4>
              <div class=" my-4">
                <p class="card-text">{{products.description}}</p>
                <h5 class="float-end price-hp">{{products.price}}</h5>
                <a href="#" class="btn btn-warning">Edit</a>
                <a href="{% url 'seller:deletepro' products.id %}" class="btn btn-warning">Delete</a>
              </div>
            </div>

          </div>

        </div>


        {% endfor %}
      </div>
    </div>
  </div>
</div>



{% endblock %}