ecommerce/common/urls.py
from django.urls import path
from . import views
app_name = 'common'
urlpatterns = [
    path('master1',views.common_master,name='master1'),
    path('home1',views.common_home,name='home1'),
    path('custlogin1',views.common_custlogin,name='custlogin1'),
    path('sellogin1',views.common_sellogin,name='sellogin1'),
    path('custreg1',views.common_custreg,name='custreg1'),
    path('selreg1',views.common_selreg,name='selreg1'),
    path('emailexist',views.email_exists,name='email_exists'),
]

ecommerce/customer/urls.py
from django.urls import path
from . import views
app_name = 'customer'
urlpatterns = [
    path('master2',views.customer_master,name='master2'),
    path('home2',views.customer_home,name='home2'),
    path('productdetail',views.customer_product_details,name='productdetail'),
    path('myorder',views.customer_myorder, name='myorder'),
    path('profile',views.customer_profile,name='profile'),
    path('change_password',views.change_password,name='change_password'),
    path('logout',views.logout,name='logout'),
    path('view_pro/<int:product_id>',views.view_products,name='viewpro'),
    path('add_to_cart/<int:product_id>',views.add_to_cart,name='addtocart'),
    path('cart',views.customer_cart,name='cart'),
    path('change_quantity',views.change_quantity,name='change_quantity')
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include ('common.urls')),
    path('customer/',include ('customer.urls')),
    path('seller/',include ('seller.urls')),
    path('school_api/',include ('school_api.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/customer/models.py
from django.db import models
from seller.models import Product
from common.models import Customer

# Create your models here.
class Cart(models.Model):
    products = models.ForeignKey(Product,on_delete=models.CASCADE, default='')
    quantity = models.IntegerField(max_length=50,default=1) 
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE, default='')
    

ecommerce/customer/views.py
from django.shortcuts import render,redirect

from common.models import Customer
from seller.models import Product
from customer.models import Cart
from .decorator import auth_customer
# Create your views here.
def customer_master(request):
    return render(request,'customer_temp/master2.html')

@auth_customer
def customer_home(request):
    return render(request,'customer_temp/home2.html')

def customer_product_details(request):
    customer_products = Product.objects.all()
    return render(request,'customer_temp/pro_details.html' , {'productlist' : customer_products})

def customer_myorder(request):
    return render(request,'customer_temp/myorder.html')

@auth_customer
def customer_profile(request):
    
    #if session_id in requst.session
        #variable=Class.objects.get (oru variable lek aa session il ulla aalde details)
     
    currentuser = Customer.objects.get(id = request.session['customer'])
    return render(request,'customer_temp/profile.html',{'user_details' : currentuser})
                        #dictionary aayit kodukum oru new variable lek :aa login cheytha aalde details html  il veran,ee variable aan html il page il call aakne
   
    

def change_password(request):
    success_msg = ''
    error_msg = ''
    if request.method == 'POST':
        old_pass = request.POST ['old_password'] 
        new_pass = request.POST ['new_password']
        confirm_pass = request.POST ['confirm_password']
       
        customer = Customer.objects.get(id = request.session['customer'])
       
        if new_pass == confirm_pass:
           if len(new_pass) >=8:
                  if customer.customer_password  == old_pass:
                    customer.customer_password = new_pass
                    customer.save()
                    success_msg = 'password changed'
                  else:
                      error_msg = 'incorrect password'
                

           else:
               error_msg = 'password should be minimum 8 characters'
        else:
           error_msg = 'Password does not match'
           

    return render(request,'customer_temp/change_password.html',{'success_msg':success_msg,'error_msg':error_msg})

def logout(request):
    del request.session['customer']
    # return render (request,'common/custlogin1.html')
    return redirect('common:custlogin1')

def view_products(request,product_id):
    viewpro = Product.objects.get(id=product_id)
    
    return render(request,'customer_temp/view_pro.html',{'view_product':viewpro})

def add_to_cart(request,product_id) :
    cart_object = Cart.objects.filter(customer_id = request.session ['customer'],products_id = product_id).exists()
    if not cart_object: 
        cart = Cart.objects.create(
            customer_id = request.session['customer'],
            products_id = product_id,    
            )
    else:
        cart = Cart.objects.get(customer_id = request.session ['customer'],products_id = product_id)    
        cart.quantity = cart.quantity + 1
        cart.save()
      
        
    return redirect ('customer:productdetail')

def customer_cart(request):
    cart = Cart.objects.filter(customer_id = request.session ['customer'])
    return render(request,'customer_temp/cart.html',{'cart_product': cart})

def change_quantity(request):
    error_msg = ''
    # success_msg = ''
    quantity = int(request.POST['quantity'])
    product_id = int(request.POST['product_id'])
    current_stock = Product.objects.get(id = product_id).current_stock
    if quantity > current_stock :
        error_msg = 'Out of stock'
    else:
        error_msg = 'In stock'
    return JsonResponse({'error_msg': error_msg})

    

ecommerce/customer/templates/customer_temp/cart.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<!-- On tables -->
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Product Image</th>
        <th scope="col">Product name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Sub Total</th>
      </tr>
    </thead>
    <tbody>
    {% for pro in cart_product %}
      <tr>
        <th><img src="{{pro.products.product_pic.url}}" alt="" height="100px" width="100px"></th>
        <th scope="row">{{pro.products.product_name}}</th>
        <td>{{pro.products.price}}</td>
        <td>{{pro.quantity}}</td>
        <td>#</td>
      </tr>
    {% endfor %}
    </tbody>
   

  </table>
  <h1>Total:</h1>
  <input type="text" name="" id=""><br><br>
  <button class="btn btn-warning">Place Order</button>
  <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
  <script>
  (document).ready(function () {
    $.ajaxSetup({
        headers: {
            "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
    })

    $('#qty').change(function () {

        $.ajax({

            type: 'POST',
            url: "{% url 'customer:change_quantity' %}",
            data: {
                'product_id': $(this).attr('data-item'),
                'quantity': $(this).val()
            },


            success: function (response) {
                let error = response.error_msg
                // let success = response.success_msg
                if (error == "In stock") {
                    $('#stock_error').html(error)
                    $('#stock_error').css('color', 'green')

                } else {
                    $('#stock_error').html(error)
                    $('#stock_error').css('color', 'red')
                }
                $('#stock_error').html(error)
                // $('#stock_success').html(success)


            }
        })
    })
})

</script>
{% endblock %}



<!-- onchange="getTotal('{{item.product.p_price}}')"
                    max="{{item.product.p_stock}}" -->

ecommerce/customer/templates/customer_temp/change_password.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<div class="container"
    style="background-color: rgb(147, 228, 147); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;height: 400px; width: 400px;border-radius: 10px;">
    <h1
        style="text-align: center; color: rgb(50, 50, 134); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-size: 30px;margin-top: 20px;">
        <u>CHANGE PASSWORD </u>
    </h1><br>
    <form method ='POST'>
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">old password</label>
            <input type="password" class="form-control" id="old_password_Field" name="old_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">new password</label>
            <input type="password" class="form-control" id="new_password_Field" name="new_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">confirm Password</label>
            <input type="password" class="form-control" id="confirm_password_Field" name="confirm_password">
        </div>

        <button type="submit" class="btn btn-success">Change password</button>
        <!-- {{ error }} {{ success }} -->
    </form>
    {{ success_msg }}
    {{ error_msg }}
</div>
{% endblock %}

ecommerce/customer/templates/customer_temp/home2.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<h1>home</h1>
{% endblock %}

ecommerce/customer/templates/customer_temp/master2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</head>

<body>
    <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'customer:home2' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customer:productdetail' %}">Product Details</a>
        </li><li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'customer:myorder' %}">My orders</a>
        </li>
     
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customer:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'customer:change_password' %}">cHANGE pASSWORD</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'customer:cart' %}">Cart</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customer:logout' %}">lOGOUT</a>
        </li>
     
      </ul>


      {% block content %}
{% endblock %}
</body>

</html>

ecommerce/customer/templates/customer_temp/myorder.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<h1>
my orders</h1>
{% endblock %}

ecommerce/customer/templates/customer_temp/pass.html
{% comment %} app password : eoijtqfkwommguqb  {% endcomment %}

ecommerce/customer/templates/customer_temp/pro_details.html
{% extends 'customer_temp/master2.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="container-fluid bg-trasparent my-4 p-3" style="position: relative;">

            <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
                {% for product in productlist %}
                <div class="col">
                    <a href="{% url 'customer:viewpro' product.id %}">
                    <div class="card h-100 shadow-sm">
                        <img src="{{ product.product_pic.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <div class="clearfix mb-3">
                            </div>
                            <h4 class="card-title text-center">{{product.product_name}}</h4>
                            <div class=" my-4">
                                <p class="card-text"></p>
                                <h5 class="float-end price-hp"></h5>
                                <a href="{% url 'customer:addtocart' product.id %}" class="btn btn-warning">Add to Cart</a>
                            </div>
                        </div>

                    </div>
                    </a>
                </div>


                {% endfor %}
            </div>
        </div>
    </div>
</div>



{% endblock %}

ecommerce/customer/templates/customer_temp/profile.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<h1>profile</h1>

<h3>name:{{user_details.customer_name}}</h3>
<h3>email:{{user_details.customer_email}}</h3>
<h3>phone:{{user_details.customer_phoneno}}</h3>
{% comment %} render il kodutha varaiable . models il koduthe {% endcomment %}
{% endblock %}

ecommerce/customer/templates/customer_temp/view_pro.html
{% extends 'customer_temp/master2.html' %}
{% load static %}
{% block content %}
<img src="{{ view_product.product_pic.url }}" alt="" width="100%" height="250px"><br>
<h1>{{view_product.product_name}}</h1>
<h3>{{view_product.description}}</h3>
<h4>{{view_product.price}}</h4>
<a href="#" class="btn btn-warning">Add to Cart</a>
<a href="#" class="btn btn-warning">Buy Now</a>
{% endblock %}